Integer gun =1;
switch on gun{

    when 1{
        System.debug('Pazartesi');
    }
    when 2{
        System.debug('Sali');
    }
    when 3{
        System.debug('Carsamba');
    }
    when 4{
        System.debug('Persembe');
    }
    when 5{
        System.debug('Cuma');
    }
    when 6{
        System.debug('Cumartesi');
    }
    when 7{
        System.debug('Pazar');
    }
    when else{
        System.debug('Uygun bir rakam giriniz.');
    }
}